
<style>
    .page-content{
        background-color: #ffffff;
    }
    .flex{
        display: flex;
    }
    .justify-content-center{
        justify-content: center;
    }
</style>
<script src="<?= config('view_static') ?>/static/page/menu.js?v=<?= time()?>" type="text/javascript"></script>
<div class="page-content header-clear-medium">
    <input id="uuid" value="<?= $uuid ?>"  hidden >
    <input id="store_id_filed" value="<?= $store["id"]?>" hidden>
    <div class="card card-style px-3 pt-1 pb-3">
        <p class="text-uppercase font-700 color-gray-dark font-10 mb-2">Store Information</p>
        <div class="d-flex">
            <div class="align-self-center">
                <h4 class="ps-2 pt-2"><?= $store["name"]?></h4>
            </div>
        </div>
        <div class="divider mt-3 mb-3"></div>

        <div class="flex gap-2 ">
            <article id="map-marker-alt">
                <div class="relative"><span class="fa-fw select-all fas "></span></div>
            </article>
            <span ><?= $store["address"]?>, <?= $store["ward"]?>, <?= $store["district"]?>, <?= $store["city"]?></span>
        </div>

        <div class="flex align-items-center gap-2 ">
            <i class="fas fa-phone-alt"></i>
            <span><?= $store["phone"]?></span>
        </div>
    </div>
    <div class="d-flex px-3 pb-3">
        <div class="align-self-center">
            <h4 class="mb-0">Categories</h4>
        </div>
    </div>
    <?php foreach ($menu as $m) : ?>
        <div class="card card-style px-3 pt-1 pb-3">
            <p class="text-uppercase font-700 color-gray-dark font-10 mb-2"></p>
            <div class="d-flex">
                <div class="align-self-center">
                    <h4 class="ps-2 pt-2"><?= $m["name"] ?></h4>
                </div>
            </div>
            <div class="divider mt-3 mb-3"></div>
            <?php foreach ($m['items'] as $item) : ?>
                <div class="d-flex mb-3">
                    <div class="align-self-center w-100">
                        <h1 class="mb-n2 font-24 font-500 opacity-70" name="name"><?= $item["name"]?></h1>
                    </div>
                    <div class="align-self-center ms-auto">
                        <h1 class="font-24 mb-0 font-500 opacity-70" name="price"><?= $item["price"]?>K</h1>
                    </div>
                </div>
            <?php endforeach ?>
            <div class="divider mb-3"></div>
            <div class="row mb-0">
                <a data-id="<?= $m["id"] ?>"  class="btn btn-s rounded-sm text-uppercase font-700 border-gray-dark color-theme add-item-btn">Add Item</a>
            </div>
        </div>
    <?php endforeach ?>
</div>





