<div class="page-content pb-0">
    <div class="card" data-card-height="cover">
        <div class="show-on-theme-dark card-center text-center">
            <h1 class="color-white font-30 font-800 mt-3"><?= $title ?></h1>
        </div>
        <div class="card-overlay bg-theme opacity-85"></div>
        <div class="card-overlay-infinite preload-img" data-src="<?= config('view_static') ?>/static/images/pictures/_bg-infinite.jpg"></div>
    </div>
</div>
